### ISSUE TITLE
Add User Puppets

### ISSUE THREAD

**Issue by pongstr** [TORO-IO/boxen#106]
- [x] Add `mjolnir` members
- [x] Add `vishnu` + `shiva` members
- [x] Add `osiris` members
- [x] Add 'ganesha' members

//cc @femee24 @devcsrj @itsvicsoto

**Comment by pongstr** [comment]
any updates on `osiris` members?

**Comment by femee24** [comment]
hi sir i, yes i will update today as well as ganesha thanks

**Comment by pongstr** [comment]
updates? shall we just remove `osiris` from releases?

**Comment by femee24** [comment]
ahm yes forgot to... my task was covered from support. but my priority task for boxen is for PRODUCTION right now i had created branch production to add github account for each prod members.. so sorry for the delay

**Comment by femee24** [comment]
PR for add ganesha members
creating commit for adding osiris members

**Comment by femee24** [comment]
PR for osiris thanks
