### ISSUE TITLE
request to install driver for usb monitor (e1649Fwu)

### ISSUE THREAD

**Issue by supraromero** [TORO-IO/boxen#135]
- [x] DisplayLink_Mac_2.3.dmg 
Download Link: http://www.displaylink.com/downloads/mac_downloads.php
- [x] Remote Desktop Applications

**Comment by pongstr** [comment]
hi, maybe we can also format the request issue? something like:

```bash
# Application Name
Name:     [application name]

# Application Link
Link:     [link]

# Application Type
# maybe we'll also add a driver class so that
# these can be installed to users who need it
# but still optional and doesn't also has to belong
# to a specific person.
Type:     [driver | dev apps| dev utilities]

# Application Description, maybe add some description
# here on where and how the app will be use. With this
# added here, questions are no long necessary.
Description:  
  [some description here]
```

With these info added on every application request,
documenting it will not be a hassle.

Also, can we limit one (1) app request per issue?

//cc @toroio @femee24 @devcsrj

**Comment by devcsrj** [comment]
Hi @pongstr . The format seems fine, but put it in the wiki or README.md for reference.

About the *one (1) app request per issue*, sounds redundant IMO. App requests are usually 4 lines of code, so adding separate Issue (consequently, PR) seems to much. My suggestion, is in 1 PR referencing 1 issue, we could just put each application addition/removal as separate commits, i.e.:
```
Format: #<issue> : [Added/Removed] <Application name> for [Group/People/Project]/<persona>
Example: #135 : Added remote desktop applications for People/supra.pp
```
Thoughts?
