### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by pongstr** [TORO-IO/boxen#139]
- Either make only two classification - `Driver` | `Application`; or
- Make a formal definition for each, like:

```bash
# Types:
#   driver  - hardware dependencies
#   app     - launched from /Applications
#   utility - launched via terminal, i.e.: `wget`, `unzip`  
Type: [ driver | app | utility ]
``` 
Reference 1 issue and just put each application (addition or removal) as a separate commits:

![screen shot 2015-07-28 at 10 12 15 am](https://cloud.githubusercontent.com/assets/3963900/8922104/2f987e8c-3511-11e5-8505-7fb7a6c7dd85.png)

props to @devcsrj for the suggestion above.

**Comment by devcsrj** [comment]
Hi @pongstr . The format seems fine, but put it in the wiki or README.md for reference.

About the *one (1) app request per issue*, sounds redundant IMO. App requests are usually 4 lines of code, so adding separate Issue (consequently, PR) seems to much. My suggestion, is in 1 PR referencing 1 issue, we could just put each application addition/removal as separate commits, i.e.:
```
Format: #<issue> : [Added/Removed] <Application name> for [Group/People/Project]/<persona>
Example: #135 : Added remote desktop applications for People/supra.pp
```
Thoughts?

**Comment by pongstr** [comment]
:+1: makes sense to me. will add it to wiki.

**Comment by devcsrj** [comment]
Also, about the `Type`. The classifications `dev apps` and `dev utilities` seems a ambiguous. 

I suggest to:
1. Either make only two classification - `Driver` | `Application`; or
2. Make a formal definition for each, like:
```
# Types:
#   driver     - hardware dependencies
#   apps     - launched from /Applications
#   utility     - launched via terminal, i.e.: `wget`, `unzip`  
Type:     [ driver | apps | utility ]
```

**Comment by pongstr** [comment]
I wasn't really sure why I added `dev utilities`. lol the format you proposed looks better.
