### ISSUE TITLE
Create a `class::drivers`

### ISSUE THREAD

**Issue by pongstr** [TORO-IO/boxen#140]
Create a `class drivers` for members that uses hardwares that don't have drivers come with OSX. In this way, drivers will be available to anyone via `boxen [hardware-driver-here]`.

**Comment by devcsrj** [comment]
This seems great! Although, I'm not yet a boxen pro... So maybe you could show reference?

**Comment by pongstr** [comment]
PR #143

**Comment by devcsrj** [comment]
+1
